name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
          python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
          python -m pip install --upgrade pip
          pip install poetry=="1.0.2"
          poetry config virtualenvs.create false
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: python -m pytest --cov=src --cov-branch --cov-fail-under=100 --cov-report=html | tee cov_report_${{ matrix.python-version }}.txt
    - name: Lint with flake8
      run: python -m flake8 src/
    - name: Upload pytest test results (html)
      uses: actions/upload-artifact@master
      with:
          name: pytest-cov-results-${{ matrix.python-version }}-html
          path: htmlcov
    - name: Upload pytest test results (plain text)
      uses: actions/upload-artifact@master
      with:
          name: pytest-cov-results-${{ matrix.python-version }}-plain-text
          path: cov_report_${{ matrix.python-version }}.txt

  display_cov:
      name: Display coverage results
      needs: pytest
      runs-on: ubuntu-latest
      strategy:
          matrix:
              python-version: [3.6, 3.7, 3.8]
      steps:
          - name: Download result from pytest job
            uses: actions/download-artifact@master
            with:
                name: pytest-cov-results-${{ matrix.python-version }}-plain-text
          - name: Print the coverage result
            shell: bash
            run: |
                value=`cat cov_report_${{ matrix.python-version }}.txt`
                echo $value

